Section abou the RoBERTa Base OpenAI detector
Ctrl-Alt-Defeat-Foundation-Models/informatiCup2024Paper pull request #10
Opened 2023-12-02 22:37 UTC by 1Maxnet1

2023-12-03 10:05 UTC, LeviUniAcc approved these changes
good so far, do you want to write a bit about how it works or is this even public?, if not maybe we write that?

2023-12-03 14:25 UTC, RaphaW commented on paper.tex
> +The \textbf{RoBERTa Base OpenAI Detector} is the output detector model of GPT-2. It was obtained by fine-tune a RoBERTa base model with the ouputs of the GPT-2 model containing 1,5 Billion parameters
```suggestion
The \textbf{RoBERTa Base OpenAI Detector} is the output detector model of GPT-2. It was obtained by fine-tuning a RoBERTa base model with the ouputs of the GPT-2 model containing 1,5 Billion parameters. A RoBERTa Base OpenAI Detector can be used to classify texts, on whether or not it is likely to be created by the GPT-2 model. It was published by OpenAI, when the weights of the GPT-2 model 1,5 Billion parameter version was released.
```

2023-12-03 14:42 UTC, EhrenbruderRoschtbraten requested changes
Looks good content-wise, only a small comment

2023-12-03 14:42 UTC, EhrenbruderRoschtbraten commented on paper.tex
> +The \textbf{RoBERTa Base OpenAI Detector} is the output detector model of GPT-2. It was obtained by fine-tune a RoBERTa base model with the ouputs of the GPT-2 model containing 1,5 Billion parameters
```suggestion
The \textbf{RoBERTa Base OpenAI Detector} is the output detector model of GPT-2. It was obtained by fine-tuning a RoBERTa base model with the outputs of the GPT-2 model containing 1,5 Billion parameters. The RoBERTa Base OpenAI Detector can be used to classify texts, on whether they are likely to be created by the GPT-2 model. It was published by OpenAI, when the weights of the GPT-2 model 1,5 Billion parameter version was released.
```

2023-12-04 12:57 UTC, EhrenbruderRoschtbraten approved these changes

2023-12-04 12:57 UTC, RaphaW approved these changes
LGTM

2023-12-04 13:31 UTC, merged