add RADAR section
Ctrl-Alt-Defeat-Foundation-Models/informatiCup2024Paper pull request #20
Opened 2023-12-28 10:27 UTC by LeviUniAcc

the citation does not work, can maybe someone show me how it goes :) i tryed to do it like this https://www.overleaf.com/learn/latex/Bibliography_management_with_bibtex but it does not work.
@RaphaW @EhrenbruderRoschtbraten

2023-12-28 12:26 UTC, EhrenbruderRoschtbraten requested changes
Some small changes

2023-12-28 12:26 UTC, EhrenbruderRoschtbraten commented on paper.tex
> +The \textbf{RADAR-Vicuna-7B} text detector is an adversarial-learning trained model introduced by TrustSafeAI. In the training stage the detector tryed to differentiate between human and ai text whil
I would write AI always in capital letters as it is a name
```suggestion
The \textbf{RADAR-Vicuna-7B} text detector is an adversarial-learning trained model introduced by TrustSafeAI. In the training stage the detector tryed to differentiate between human and AI text while a paraphraser trained to make the text more human.
```

2023-12-28 12:26 UTC, EhrenbruderRoschtbraten commented on paper.tex
> +The Ai-generated text for learning is extracted by the LLM Vicuna-7B-v1.1 written by LMSYS Org \cite{hu2023radar}.
```suggestion
The AI-generated text for learning is extracted by the LLM Vicuna-7B-v1.1 written by LMSYS Org \cite{hu2023radar}.
```

2023-12-29 15:09 UTC, 1Maxnet1 approved these changes
LGTM, two remaining issues.

2023-12-29 15:09 UTC, 1Maxnet1 commented on paper.tex
> +The \textbf{RADAR-Vicuna-7B} text detector is an adversarial-learning trained model introduced by TrustSafeAI. In the training stage the detector tryed to differentiate between human and AI text whil
I would propose to fix the typo and replace the the with an a to reduce the amounts of "the" in the sentence.
```suggestion
The \textbf{RADAR-Vicuna-7B} text detector is an adversarial-learning trained model introduced by TrustSafeAI. In the training stage a detector tried to differentiate between human and AI text while a paraphraser trained to make the text more human.
```

2023-12-29 15:28 UTC, RaphaW approved these changes
LGTM, cannot see the citation rn, but we can fix that later

2023-12-29 15:57 UTC, merged