add cmd line interface and google collab description
Ctrl-Alt-Defeat-Foundation-Models/informatiCup2024Paper pull request #52
Opened 2024-01-30 12:33 UTC by LeviUniAcc

add some infos how we execuated our pipelines

2024-01-30 16:11 UTC, EhrenbruderRoschtbraten reviewed
Looks good, only some small comments

2024-01-30 16:11 UTC, EhrenbruderRoschtbraten commented on paper.tex
> +For ease of use and low time consumption we implemented a simple python command line interface, that makes it easy to define a pipeline consisting of a generator, processor and evaluator. It is also
```suggestion
For the ease of use and low time consumption we implemented a simple python command line interface, that makes it easy to define a pipeline consisting of a generator, processor and evaluator. It is also possible to enter multiple processors for one pipeline, to stack and apply them together on the content.
```

2024-01-30 16:11 UTC, EhrenbruderRoschtbraten commented on paper.tex
> +The resulting pipelines especially for the images were hardware expensive and could not be runn efficiently on our own machines. We chose to use the free google collab recources, consisting of a NVID
```suggestion
The resulting pipelines, especially for the images, were very resource intensive and could not be runned efficiently on our own machines. We chose to use the free google collab recources, consisting of a NVIDIA Tesla T4 GPU that would speed up the pipelines up to 40x compared to our local execution time. 
```

2024-02-02 11:59 UTC, RaphaW approved these changes
One minor adjustment

2024-02-02 11:59 UTC, RaphaW commented on paper.tex
> +The resulting pipelines, especially for the images, were very resource intensive and could not be runned efficiently on our own machines. We chose to use the free google collab recources, consisting
```suggestion
The resulting pipelines, especially for the images, were very resource intensive and could not be runned efficiently on our own machines. We chose to use the free Google Colab recources, consisting of a NVIDIA Tesla T4 GPU that would speed up the pipelines up to 40x compared to our local execution time. 
```

2024-02-03 17:51 UTC, 1Maxnet1 reviewed
Thanks for the paragraphs, left two comments.

2024-02-03 17:51 UTC, 1Maxnet1 commented on paper.tex
> +For the ease of use and low time consumption we implemented a simple python command line interface, that makes it easy to define a pipeline consisting of a generator, processor and evaluator. It is a
I would add something like the following. The point I find is missing, is the fact that the software allows us to easily manage experiments, as we have to enter one command to run a hole experiment. 
```suggestion
For the ease of use, low time consumption and easy management of our experiments we implemented a simple python command line interface, that allows it to define a pipeline consisting of a generator, processor and evaluator. It is also possible to enter multiple processors for one pipeline, to stack and apply them together on the content.
```

2024-02-03 17:51 UTC, 1Maxnet1 commented on paper.tex
> +The resulting pipelines, especially for the images, were very resource intensive and could not be runned efficiently on our own machines. We chose to use the free google collab recources, consisting
Fixed two additional typos. Also I would add the aspect of having a consistent environment for the different environments.
```suggestion
The resulting pipelines, especially for the images, were very resource intensive and could not be run efficiently on our own machines. We chose to use the free Google Colab resources, consisting of a NVIDIA Tesla T4 GPU that would speed up the pipelines up to 40x compared to our local execution time and allowed to have the same environment for all experiments. 
```

2024-02-05 12:21 UTC, EhrenbruderRoschtbraten requested changes
Made two small adjustements to @1Maxnet1 comment

2024-02-06 14:12 UTC, LeviUniAcc commented on paper.tex
> +The resulting pipelines, especially for the images, were very resource intensive and could not be runned efficiently on our own machines. We chose to use the free google collab recources, consisting
change in maxnets request

2024-02-06 14:21 UTC, 1Maxnet1 approved these changes
LGTM

2024-02-06 14:30 UTC, EhrenbruderRoschtbraten reviewed
small comments

2024-02-06 14:30 UTC, EhrenbruderRoschtbraten commented on paper.tex
> +For the ease of use and low time consumption we implemented a simple python command line interface, that makes it easy to define a pipeline consisting of a generator, processor and evaluator. It is a
```suggestion
For the ease of use and low time consumption we implemented a simple python command line interface, that makes it easy to define a pipeline consisting of a generator, processor and evaluator. It is also possible to enter multiple processors for one pipeline to stack and apply them together on the content.
```

2024-02-06 14:30 UTC, EhrenbruderRoschtbraten commented on paper.tex
> +The resulting pipelines, especially for the images, were very resource intensive and could not be run efficiently on our own machines. We chose to use the free Google Colab resources, consisting of a
```suggestion
The resulting pipelines, especially for images, were very resource intensive and could not be run efficiently on our own machines. We chose to use the free Google Colab resources, consisting of a NVIDIA Tesla T4 GPU that speeds up the pipelines up to 40x compared to our local execution time and allowed us to use the same environment for all experiments. 
```

2024-02-06 14:33 UTC, EhrenbruderRoschtbraten approved these changes
Wird schon passen denk

2024-02-06 14:33 UTC, merged