Initial draft of the method section
Ctrl-Alt-Defeat-Foundation-Models/informatiCup2024Paper pull request #9
Opened 2023-12-02 22:26 UTC by 1Maxnet1

2023-12-03 10:02 UTC, LeviUniAcc approved these changes
i like it so far

2023-12-03 14:22 UTC, RaphaW commented on paper.tex
> +To test and evaluate the effect of different data augmentation techniques on the detection capabilities of fake image or text detectors, we created a pipeline of three components: The first component
```suggestion
To test and evaluate the effect of different data augmentation techniques on the detection capabilities of fake image or text detectors, we created a pipeline of three components: The first component is a generator, which is a model capable of generating fake images or texts. The second component is a processor which augments the data a specified method, after inputting a generated image or text. The last component contains a detector, which returns whether the input is a fake artefact or a real one. This way we can compare it to the ground truth, to evaluate the capabilities of the detector. By comparing the results with augmented artefacts and the generated ones without augmentation, we can see how effective different techniques are to trick ai detectors.
```

2023-12-03 14:39 UTC, EhrenbruderRoschtbraten requested changes

2023-12-03 14:39 UTC, EhrenbruderRoschtbraten commented on paper.tex
> +To test and evaluate the effect of different data augmentation techniques on the detection capabilities of fake image or text detectors, we created a pipeline of three components: The first component
Would do it like this:
```suggestion
To test and evaluate the effect of different data augmentation techniques on the detection capabilities of fake image or text detectors, we created a pipeline of three components: The first component is a generator, which is a model capable of generating fake images or texts. The second component is a processor agmenting the input data, which would can be an image or an text, through a specified method. The last component is a detector, which suggests an input being either real or fake. This way we can compare it to the ground truth, to evaluate the capabilities of the detector. By comparing the results with augmented artefacts and the generated ones without augmentation, we can evaluate the effectiveness of different AI detector-tricking techniques.
```

2023-12-04 13:23 UTC, EhrenbruderRoschtbraten approved these changes
Fine, but can incorporate the comment when it sounds good to you.

2023-12-04 13:23 UTC, EhrenbruderRoschtbraten commented on paper.tex
> +To test and evaluate the effect of different data augmentation techniques on the detection capabilities of fake image or text detectors, we created a pipeline of three components: The first component
```suggestion
To test and evaluate the effect of different data augmentation techniques on the detection capabilities of fake image or text detectors, we created a pipeline of three components: The first component is a generator, which is a model capable of generating fake images or texts. The second component is a processor augmenting the given image or text through a specified method. The last component is a detector, which suggests an input being either real or fake. This way we can compare it to the ground truth, to evaluate the capabilities of the detector. By comparing the results with augmented artefacts and with the generated ones without augmentation, we can evaluate the effectiveness of different AI detector-tricking techniques.
```

2023-12-04 13:32 UTC, RaphaW approved these changes
Nothing new expect a minor change

2023-12-04 13:32 UTC, RaphaW commented on paper.tex
> +To test and evaluate the effect of different data augmentation techniques on the detection capabilities of fake image or text detectors, we created a pipeline of three components: The first component
```suggestion
To test and evaluate the effect of different data augmentation techniques on the detection capabilities of fake image or text detectors, we created a pipeline of three components: The first component is a generator, which is a model capable of generating fake images or texts. The second component is a processor which augments the data through a specified method, after given a generated image or text. The last component is a detector, which suggests an input being either real or fake. This way we can compare it to the ground truth, to evaluate the capabilities of the detector. By comparing the results with augmented artefacts and with the generated ones without augmentation, we can evaluate the effectiveness of different AI detector-tricking techniques.
```

2023-12-04 13:44 UTC, merged